### ISSUE TITLE
I got crash following crash on a video 

### ISSUE THREAD

**Issue by asadaltaf583** [AndroidDeveloperLB/VideoTrimmer#17]
java.lang.OutOfMemoryError: Failed to allocate a 749306784 byte allocation with 11539821 free bytes and 244MB until OOM, target footprint 23079645, growth limit 268435456
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:284)
        at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
        at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
        at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
        at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
        at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
        at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
        at com.googlecode.mp4parser.BasicContainer.getBoxes(BasicContainer.java:80)
        at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
        at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
        at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)

**Comment by AndroidDeveloperLB** [comment]
What are the steps? Where is the video file you've tried to handle? What are the environment details?

**Comment by asadaltaf583** [comment]
Samsung Galaxy A13 with android 13 version. Select this video from gallery
and try to trim it.This video has 22 seconds length trim it for 10 or 15
seconds app will crash

>

**Comment by AndroidDeveloperLB** [comment]
Please put a sample video (hopefully short one) that causes it to crash
